# LYRA-4 build overlay:  west build ... -- -DOVERLAY... use: -DEXTRA_CONF_FILE=lyra.conf
CONFIG_SP1_PLAITS=n
CONFIG_SP1_LYRA=y
CONFIG_SP1_MIDI=n
CONFIG_SP1_USB_AUDIO=n
CONFIG_SP1_USB_PRODUCT="LYRA-4"
CONFIG_SP1_USB_MANUFACTURER="Dreambored"
